### ISSUE TITLE
[iOS] Viewport is null on iOS

### ISSUE THREAD

**Issue by simkepal** [matanshukry/flutter_google_places_sdk#15]
Hello,

I need some help. For me on iOS viewport is returning null. Am I doing something wrong?

final List<PlaceField> fields = [
PlaceField.Viewport,
PlaceField.Location,
];
FetchPlaceResponse response = await _places.fetchPlace(placeId, fields: fields);

Thank you for your help!

**Comment by Milvintsiss** [comment]
Any update on this?

It's seems that the iOS implementation has not been finished since [this line](https://github.com/matanshukry/flutter_google_places_sdk/blob/221b20e81d17df9a0845ef602bf993c6bb920dbb/flutter_google_places_sdk_ios/ios/Classes/SwiftFlutterGooglePlacesSdkIosPlugin.swift#L173) is commented out.

**Comment by matanshukry** [comment]
It has not. I don't have a mac so I can't really develop or even test this at this moment.
PRs are more than welcome though.

**Comment by Milvintsiss** [comment]
OK. I will take a look at it and do a PR if I manage it out :)

**Comment by matanshukry** [comment]
Implemented.

Thanks @Milvintsiss !
