### ISSUE TITLE
Support for other platforms (macOS / Linux)

### ISSUE THREAD

**Issue by voicubabiciu** [matanshukry/flutter_google_places_sdk#26]
Hello!
Any plans of supporting **macOS**, **Windows**, and **Linux** platforms in the future?
Thanks!

**Comment by matanshukry** [comment]
@voicubabiciu Implemented windows - see https://pub.dev/packages/flutter_google_places_sdk .

I don't see macOS or Linux coming any time soon, considering I don't use either and this package is revenue-free.

But PRs are more than welcome.

**Comment by voicubabiciu** [comment]
Hello @matanshukry, could you look at the PR I've opened?

**Comment by matanshukry** [comment]
Quick update:
* Refactored window implementation to a new http package, since it will be the same implementation for window/linux/macos.
* Used the http impl with the window
* Linux is now implemented (using http)
* Macos is now left to be implemented by @voicubabiciu if desired (or by me if not / in a few days)

**Comment by matanshukry** [comment]
Macos implemented
