### ISSUE TITLE
Places API (new)

### ISSUE THREAD

**Issue by JaseElder** [matanshukry/flutter_google_places_sdk#65]
Hi,

Do you have any plan to migrate to the new Places API?

https://developers.google.com/maps/documentation/places/web-service/migrate-overview

**Comment by kirpit** [comment]
I believe the package will eventually support the new API soon or late.

However, I also would like to note here that there are some of us don't want to migrate to new Places API mostly because of the new pricing.

**Comment by kirpit** [comment]
Yes it's relatively cost effective for those because it can now define the returning fields from any of the search types, not only "Place Details". However, place autocomplete and query autocomplete seems to be dropped completely:

![image](https://github.com/matanshukry/flutter_google_places_sdk/assets/1009931/4ae878ba-ffea-433f-bf95-fd1165b25198)
https://developers.google.com/maps/documentation/places/web-service/op-overview

In other terms, I have to do a Text Search instead of autocomplete, which would cost $30 per 1000 search instead of 17$ with basic info such as place display name, address and type.
